export const TOGGLETAB = 'TOGGLETAB';
export const CHANGECHARTDAY = 'CHANGECHARTDAY';
export const CHANGECHARTTYPE = 'CHANGECHARTTYPE';
export const REQUEST_CHART_DATA = 'REQUEST_ARTICLE_LIST';
export const CHART_DATA = 'CHART_DATA';
    